#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
批量替换导航栏和用户菜单的中文
"""

import re
from pathlib import Path

# 导航菜单翻译
nav_translations = {
    '首页': 'Home',
    '新闻中心': 'News',
    '价格资讯': 'Price Info',
    '讨论区': 'Forum',
    '二手市场': 'Second-hand Market',
    '平台市场': 'Platform Market',
    '官方商城': 'Official Store',
    '在线客服': 'Online Support',
    'AI推荐': 'AI Recommendations',
    '交易对话': 'Messages',
}

# 用户菜单翻译
user_translations = {
    '请登录': 'Please Login',
    '我的物品': 'My Items',
    '我的收藏': 'My Favorites',
    '我的评价': 'My Reviews',
    '搜寻通知': 'Search Notifications',
    '退出登录': 'Logout',
    '免费刊登': 'Post Free Ad',
}

# 其他常见翻译
other_translations = {
    'title="交易对话"': 'title="Messages"',
    'title="私讯"': 'title="Private Messages"',
    '二手买卖专区': 'Second-hand Trading Zone',
    '返回菜单': 'Back to Menu',
    '官方商品分类': 'Official Product Categories',
    '分类将通过 JavaScript 动态生成': 'Categories will be dynamically generated by JavaScript',
    '官方商城正式上线！': 'Official Store Now Online!',
    '正品保证，官方直营，品质服务，值得信赖！': 'Genuine products, official direct sales, quality service, trustworthy!',
}

def translate_file(file_path):
    """翻译单个文件"""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        original = content
        
        # 替换导航菜单
        for chinese, english in nav_translations.items():
            content = content.replace(chinese, english)
        
        # 替换用户菜单
        for chinese, english in user_translations.items():
            content = content.replace(chinese, english)
        
        # 替换其他常见文本
        for chinese, english in other_translations.items():
            content = content.replace(chinese, english)
        
        if content != original:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"✓ Translated: {file_path.name}")
            return True
        return False
    except Exception as e:
        print(f"✗ Error processing {file_path.name}: {e}")
        return False

# 需要处理的文件
files_to_process = [
    'frontend/secondary.html',
    'frontend/forum.html',
    'frontend/platform-market.html',
    'frontend/online-support.html',
    'frontend/AI-Setup-Recommend.html',
    'frontend/friendlist.html',
]

if __name__ == '__main__':
    translated = 0
    for file_path in files_to_process:
        path = Path(file_path)
        if path.exists():
            if translate_file(path):
                translated += 1
        else:
            print(f"✗ File not found: {file_path}")
    
    print(f"\nCompleted! Translated {translated} files.")











